language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
env:
  - DJANGO='Django>=2.2,<2.3'
  - DJANGO='Django>=3.0,<3.1'
  - DJANGO='Django>=3.1,<3.2'
  - DJANGO='Django>=3.2,<3.3'
  - DJANGO='Django>=4.0,<4.2'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install --quiet $DJANGO
  - pip install --quiet coverage
  - pip install --quiet flake8
  - pip install -e .
before_script:
  - flake8 --exclude=migrations --ignore=W291,W503,E501,F401,F403 moderation tests
script:
  - coverage run setup.py test
after_success:
  - coverage report
  - pip install --quiet --use-mirrors coveralls
  - coveralls
