language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
env:
  - DJANGO='Django>=3.2,<3.3'
  - DJANGO='Django>=4.0,<4.1'
  - DJANGO='Django>=4.1,<4.2'
  - DJANGO='Django>=4.2,<4.3'
  - DJANGO='https://github.com/django/django/archive/main.tar.gz'
matrix:
  exclude:
    - python: "3.7"
      env: DJANGO='https://github.com/django/django/archive/main.tar.gz'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/main.tar.gz'
install:
  - pip install --quiet $DJANGO
  - pip install --quiet coverage
  - pip install --quiet flake8
  - pip install -e .
before_script:
  - flake8 --exclude=migrations --ignore=W291,W503,E501,F401,F403 moderation tests
script:
  - coverage run setup.py test
after_success:
  - coverage report
  - pip install --quiet --use-mirrors coveralls
  - coveralls
